### PR TITLE
Split up ssa.Program from the base interface

### LINKED ISSUE #5: Avoid work with linters that don't need ssa
If a linter doesn't need ssa it's a bit silly to load all of that if no other linters need it.

Right now, the interface doesn't let linters specify what information they need.

For simplicity, let's not include type info here. `go/loader` has type info at its core, and I don't believe any linter is particularly useful only with `go/ast`.

### PR DESCRIPTION
**Pull request by mvdan**
Make it optional, depending on whether or not each checker
implementation needs SSA or not.

Fixes #5.

### CODE REVIEW

**Comment by mvdan** [comment]
@thomasheller @bradleyfalzon PTAL. Ignore the build failure; once we're happy with this I'll update my linters accordingly.

Some open questions:

`ProgramSSA` or `SSAProgram` for the method?

Does the name `WithSSA` make sense? Should it include `Checker` in the name?

Do we want to include merged interfaces, like:

```go
type CheckerSSA interface {
    Checker
    WithSSA
}
```

My only worry with the last point is that if the matrix gets bigger, we don't want to include `CheckerFuncBodiesSSA` and such.

**Comment by thomasheller** [comment]
Just a thought: This could also work in a lazy-loading kind of way. We could pass the linters a more generic `GoSource` interface, like so:

```go
type Checker interface {
        Check(GoSource) ([]Issue, error)
}

type GoSource interface {
        Files() []string
        Program() *loader.Program
        SSA() *ssa.Program
}
```

Only if one of the linters actually requests one of the values, `metalint` does the work and also caches the result for subsequent linters to use.

But then, this could go wrong sooner or later, for instance if the linters can specify which function bodys they need type-checked (#8). So I would rather like to see a clean way how `metalint` can query each linter about its expectations before it runs any of them.

Another thought: Shouldn't we be using channels somehow? We have at least two steps here, `go/loader` and SSA. It would be nice if linters could already do their work on `loader.Program`, while other linters requiring SSA block until `ssa.Program` is available...

**Comment by mvdan** [comment]
> So I would rather like to see a clean way how metalint can query each linter about its expectations before it runs any of them.

Agreed - I don't think the linters should be in control of what happens and when here. That's why I'm going for interfaces that let the linters say what they need.

> Another thought: Shouldn't we be using channels somehow?

Remember that channels mean goroutines. It adds overhead to the API.

> We have at least two steps here, go/loader and SSA. It would be nice if linters could already do their work on loader.Program, while other linters requiring SSA block until ssa.Program is available...

Both `go/loader` and `go/ssa` are going to be using all of your CPU. I don't think we should optimize for anything like this. It's likely that it will complicate the API and will mean no performance gains for `metalint`.

**Comment by bradleyfalzon** [comment]
I was thinking along the lines of:

```go
type ProgramChecker func (*loader.Program) ([]Issue, error)

type SSAChecker func (*ssa.Program) ([]Issue, error)
```

I haven't put any thought into this, but I was more thinking these would be func signatures, not interfaces. So a meta linter would look like:

```go
var programLinters = [...]struct {
	name    string
	checker lint.ProgramChecker
}{
	{"unparam", unparam.Check},
	{"interfacer", interfacer.Check},
}

var ssaLinters = [...]struct {
	name    string
	checker lint.SSAChecker
}{
	{"unparam", unparamSSA.Check},
	{"interfacer", interfacerSSA.Check},
}
```

Having thought about this a little more, I don't think I like it, as it's perhaps only slightly simpler for library authors, but it's harder to implement in meta linters. But there's no risk to library authors if they already have an exported Check function that doesn't implement our interface, and they don't want the breaking change.

I'm probably -1 on this method, adding it here in case others have other thoughts.

**Comment by mvdan** [comment]
> I'm probably -1 on this method, adding it here in case others have other thoughts.

I'm not in favor of func signatures as they're just not possible to extend. They also don't easily allow adding optional methods such as #8.

Also, SSA checkers would still need the `*loader.Program`. So `ssa` is a layer on top of `go/loader`, not a separate interface.

Thanks for both of your inputs; neither had occurred to me, but I think neither is a good way forward. I'm not 100% confident on mine, but we need to decouple SSA somehow before 1.0.

**Comment by thomasheller** [comment]
@mvdan We can only do so much. The merged interface approach is probably cleanest, but ultimately it also has limitations (cases like `CheckerFuncBodiesSSA` which we wouldn't want, as you mentioned). So basically, we should define a reasonable scope for 1.0, and if something unexpectedly more complex and flexible is going to happen, it probably has to wait for 2.0.

**Comment by mvdan** [comment]
Note that it isn't merged yet :) but will be soon.

**Comment by mvdan** [comment]
Merged and `cmd/metalint` updated. Also updated my two linters.

**Pull request merged**
